"""Build an isolated public corpus only from an explicitly reviewed hash allowlist."""
import argparse
import hashlib
import json
from pathlib import Path
import shutil

from buna.public_corpus import load_corpus


def seed(audit_path: Path, expected_sha: str, staging: Path, destination: Path):
    raw = audit_path.read_bytes()
    if hashlib.sha256(raw).hexdigest() != expected_sha:
        raise ValueError("Redistribution audit fingerprint mismatch.")
    audit = json.loads(raw)
    records = {entry["reference_id"]: entry for entry in audit["entries"]}
    papers = []
    for allowed in audit["allowlist"]:
        entry = records[allowed["reference_id"]]
        if entry["allowed_for_public_seed_if_conditions_met"] is not True:
            raise ValueError("Unapproved public source.")
        name, digest = allowed["filename"], allowed["sha256"]
        if name not in {digest + ".pdf", digest + ".txt"}:
            raise ValueError("Unsafe corpus filename.")
        file = staging / name
        if file.is_symlink() or hashlib.sha256(file.read_bytes()).hexdigest() != digest:
            raise ValueError("Public source fingerprint mismatch.")
        credits = [entry["required_attribution_text"], entry.get("copyright_notice") or "",
                   entry["modifications_and_omissions"],
                   "Similarity highlighting and excerpt selection are generated by Paper Overlap Detector; no author or publisher endorsement is implied."]
        for extra in entry["additional_attributions"]:
            credits.append(extra.get("attribution_text") or "\n".join(str(v) for v in extra.values()))
            credits.extend(extra.get("copyright_notices_already_retained_in_text", []))
        papers.append({
            "sha256": digest, "filename": name, "title": entry["title"],
            "license": allowed["license_id"], "license_url": allowed["license_url"],
            "source_url": entry["source_url"], "version": entry["version_under_review"],
            "attribution": "\n\n".join(c for c in credits if c),
            "license_evidence": entry["license"]["scope"],
            "redistribution_approved": True,
        })
    manifest = {"schema_version": 1, "purpose": "public-redistribution",
                "audit_sha256": expected_sha, "papers": papers}
    if destination.exists():
        if json.loads((destination / "manifest.json").read_text()) != manifest:
            raise ValueError("Destination already contains a different corpus; use a new release directory.")
        return load_corpus(destination)
    destination.mkdir(parents=True)
    for paper in papers:
        shutil.copyfile(staging / paper["filename"], destination / paper["filename"])
    (destination / "manifest.json").write_text(json.dumps(manifest, ensure_ascii=False, indent=2))
    return load_corpus(destination)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--audit", required=True, type=Path)
    parser.add_argument("--expected-sha256", required=True)
    parser.add_argument("--staging", required=True, type=Path)
    parser.add_argument("--destination", required=True, type=Path)
    args = parser.parse_args()
    papers = seed(args.audit, args.expected_sha256, args.staging, args.destination)
    print(json.dumps({"public_papers": len(papers), "audit_sha256": args.expected_sha256}))
